package:
  name: gcc-arm-none-eabi
  version: 8.2019.q3.update

source:
  url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-mac.tar.bz2 # [osx]
  sha256: fc235ce853bf3bceba46eff4b95764c5935ca07fc4998762ef5e5b7d05f37085 # [osx]
  url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2 # [linux64]
  sha256: b50b02b0a16e5aad8620e9d7c31110ef285c1dde28980b1a9448b764d77d8f92 # [linux64]
  url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-win32.zip # [win]
  sha256: 94913fe2414b424d81cd53fbf906f1865444c634260b7544b6098eb2a74dae1c # [win]

build:
  string: '1'

test:
  commands:
    - arm-none-eabi-gcc --version

about:
  home: https://developer.arm.com/open-source/gnu-toolchain/gnu-rm
  license: GPL
  summary: GNU Arm Embedded Toolchain
